-- 코드를 입력하세요
SELECT UGB.TITLE, UGB.BOARD_ID, UGR.REPLY_ID, UGR.WRITER_ID, UGR.CONTENTS, DATE_FORMAT(UGR.CREATED_DATE, '%Y-%m-%d') as CREATED_DATE 
FROM USED_GOODS_BOARD AS UGB, USED_GOODS_REPLY AS UGR
WHERE UGB.BOARD_ID = UGR.BOARD_ID
AND UGB.CREATED_DATE BETWEEN '2022-10-01' AND '2022-10-31'
ORDER BY UGR.CREATED_DATE ASC, UGB.TITLE ASC;